# Generated by Django 2.2.4 on 2019-08-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190807_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforagency',
            name='agency',
            field=models.ForeignKey(help_text='Выберите сеть предприятия и сохраните, для получения списка предприятий', on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.Agency', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='productforagency',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productforagency',
            name='product',
            field=models.ForeignKey(help_text='Выберите сеть предприятия и сохраните, для получения списка товаров', on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.Product', verbose_name='Товар'),
        ),
    ]
