# Generated by Django 2.2.4 on 2019-08-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('products', '0008_auto_20190809_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Organization',
        ),
        migrations.AlterField(
            model_name='connector',
            name='agency',
            field=models.ForeignKey(help_text='Выберите сеть предприятия и сохраните, для получения списка предприятий', on_delete=django.db.models.deletion.CASCADE, related_name='connector', to='products.Organization', verbose_name='Предприятие'),
        ),
    ]
