# Generated by Django 2.2.4 on 2019-08-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190809_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='agency',
            new_name='organization',
        ),
    ]
